#!/bin/bash
set -e

# Paths
bam_dir="/mnt/LHDD1/GTEX_Hippocampus"
BAM_LIST="$bam_dir/Hippocampus_255bamfiles.txt"
LOG_DIR="logs"
OUT_DIR="counts"

# Create output directories
mkdir -p "$LOG_DIR" "$OUT_DIR"

# Define Jobs to Run (set based on the resources: better to be conservative)
JOBS=10

# Annotation files 
gene_gtf="/mnt/data2/GTEX/TEcount_test/GTF_files/cleaned_gene_annotation.gtf"
TE_gtf="/mnt/data2/GTEX/TEcount_test/GTF_files/GRCh38_GENCODE_rmsk_TE.gtf"

#Define strandedness
TETranscripts_strandess="no"

# Path to TEcount
TEcount="/home/habtemar/tools/TEtranscripts/venv/bin/TEcount"



echo "Starting TEcount for all BAM files..."
echo "Using $JOBS parallel jobs."

# Run TEcount in parallel
cat "$BAM_LIST" | parallel -j "$JOBS" --joblog "$LOG_DIR/parallel_joblog.txt" \
'/usr/bin/time -v '"$TEcount"' \
  --BAM '"$bam_dir"'/{} \
  --GTF '"$gene_gtf"' \
  --TE '"$TE_gtf"' \
  --project '"$OUT_DIR"'/\{/.} \
  --mode multi \
  --sortByPos \
  --stranded '"$TETranscripts_strandess"' \
  > '"$LOG_DIR"'/\{/.}.out 2> '"$LOG_DIR"'/\{/.}.err'
